### ISSUE TITLE
ODROID C2: U-boot is not buildable on any platform other than x86-64

### ISSUE THREAD

**Issue by OtherCrashOverride** [hardkernel/u-boot#23] opened 2016-05-01 15:13 UTC
U-boot currently has x86-64 (64bit) binary tools from Amlogic. An example of this is:
https://github.com/hardkernel/u-boot/blob/odroidc2-v2015.01/fip/fip_create

Although ARM provides an open source version, it is not compatible since the Amlogic version is customized.  Source code for these essential build utilities needs to be provides so that u-boot can be built on ARM or x86 (32bit) platforms.

**Comment by fboudra** [comment] 2016-06-01 08:37
I assume fip_create is coming from ATF: https://github.com/ARM-software/arm-trusted-firmware/tree/master/tools/fip_create

It's worth asking Amlogic if there's any modification to the source code.

**Comment by tobetter** [comment] 2016-06-01 11:16
Do we need the binary which can run other platform, i386, armhf?

**Comment by fboudra** [comment] 2016-06-01 12:13
@tobetter I don't think so. If you can confirm the source code is coming from ATF unmodified, just add the source code to the tree. Users can build from source if they need i386, armhf or arm64 binary.

**Comment by tobetter** [comment] 2016-06-01 12:26
@fboudra AMLogic provided only prebuilt binary without their source, my understanding is that they have their own change for boot area. Need double check whether they can provide its source code or patch. I am trying to recall the discussion about 'fip_create' whether ARM source code can be used.

**Comment by OtherCrashOverride** [comment] 2016-06-03 03:22
> Although ARM provides an open source version, it is not compatible since the Amlogic version is customized.

I tested the ATF version before posting this issue.  Neither the current or older versions are compatible.

**Comment by bkrepo** [comment] 2016-06-03 06:31
I already did this work. I am just waiting for the confirmation from  my boss and Amlogic.
If they will not allow open the fip_create source code, then I will give the fip_create aarch64 binary at least. Please wait until next week. :-)

**Comment by bkrepo** [comment] 2016-06-07 01:35
Merged & Changed Makefile.

https://github.com/hardkernel/u-boot/commit/3a2dd09540d3639671d86145336f400ec07b1a4e

**Comment by fboudra** [comment] 2016-06-07 04:20
Thanks!

**Comment by tobetter** [comment] 2016-06-07 13:44
@fboudra I'm curious if you have a plan to put C2 Uboot to your build queue for public release.

**Comment by fboudra** [comment] 2016-06-07 13:58
@tobetter it wasn't my plan to make a public release, it's for our engineering. But if you're interested into a CI loop running natively on arm64 for C2, I can do that and make the build artifacts available.

**Comment by tobetter** [comment] 2016-06-07 14:16
@fboudra Thanks for quick response, it would be great if Uboot for C2 can be parted on your build. Obviously it's upon your decision, just some are interested in. :)

**Comment by ShorTie8** [comment] 2016-06-17 07:27
I am still having problems building this on a C2
Is fip/gxb/aml_encrypt_gxb a x86-64 only blob too ??

`../fip/gxb/aml_encrypt_gxb: ../fip/gxb/aml_encrypt_gxb: cannot execute binary file
/root/buildroot-smoothwall/buildroot/output/build/uboot-3edccd18784aef602a50040b24acdf3adbb7781a/Makefile:877: recipe for target 'boot.bin' failed
make[2]: *** [boot.bin] Error 126
`

**Comment by bkrepo** [comment] 2016-06-17 08:11
@ShorTie8 Thank you for the report. I confirmed the problem.
Of course, I tested a lot U-boot build process on arm64 environment(C2 Ubuntu) before this issue is closed. I cannot understand why I did not face the problem when I tried building U-boot at that time.

We will check whether Amlogic can open the aml_encrypt source code or it is unnecessary.

**Comment by bkrepo** [comment] 2016-07-18 01:31
For native u-boot build, qemu-user enables C2 Linux to execute x86-64 elf file:

```
$ sudo apt-get install qemu-user
$ git clone https://github.com/hardkernel/u-boot.git -b odroidc2-v2015.01
$ cd u-boot
$ make odroidc2_config
$ make
```

Maybe I didn't face the aml_encrypt build error when I tested u-boot native build before because I installed the qemu for the kvm virtualization test. So, I confused this issue is solved.

ref> http://forum.odroid.com/viewtopic.php?f=135&t=21922&sid=fe84f400d846d8143b8612eb0353c21d&p=151128#p151130

**Comment by bkrepo** [comment] 2016-10-12 02:41
Unfortunately, we cannot get the aml_encrypt source files. So, if anyone want to build on other platform, please use the qemu emulator as my previous comment.

**Closed as completed by bkrepo** 2016-10-12 02:41 UTC

**Comment by afaerber** [comment] 2017-04-21 06:08
For anyone facing the `aml_encrypt_gxb` issue on aarch64 hosts: I have written a tool [amlbootsig](https://github.com/afaerber/meson-tools) that appears to work sufficiently for the Odroid-C2.

**Comment by OtherCrashOverride** [comment] 2017-04-21 23:27
I ran across that before but was unsure of the status.  Thanks for pointing it out.
